spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-ccy-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-ccy-test
#以utf-8格式保存