spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro01?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useLocalSessionState=true
    username: root
    password: root123456
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 10      # 初始化连接数
      max-total: 5         #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
mybatis:
 # config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ccy.springclod.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
#debug: true
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001   # 服务别名处理
    prefer-ip-address: true                   # 访问路径显示ip地址
#服务info信息
info:
  app.name: ccy-microservicecloud
  company.name: www.ccy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
---
 server:
  port: 8002

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro02?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useLocalSessionState=true
    username: root
    password: root123456
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 10      # 初始化连接数
      max-total: 5         #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
mybatis:
 # config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ccy.springclod.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
#debug: true
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001   # 服务别名处理
    prefer-ip-address: true                   # 访问路径显示ip地址
#服务info信息
info:
  app.name: ccy-microservicecloud
  company.name: www.ccy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#以utf-8格式保存